# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Validate a Pull Request and build PKG
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.21
        with:
          debug: true
          target: 'pkgbuild'
          pkgname: 'oxp-sensors'

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: oxp-sensors-v0.1.r0.g0e0a85f
          files: oxp-sensors/oxp-sensors-v0.1.r0.g0e0a85f-1-x86_64.pkg.tar.zst
